// js/data.js

/* Data needs to be cleaned before being imported tok here.
  Some cases are handled by the website like:
    Case sensitivity: PLAYER_1 = Player_1 or AFFINITY vs Affinity
    Whitespace at the end of a string
  But anything else needs to be handled before uploading to Data
*/
export const cleanedData = [
    {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 1,
    "Player": "Player1",
    "Deck": "Affinity",
    "Wins": 8,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 1,
    "Player": "Player1",
    "Deck": "Affinity",
    "Wins": 8,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 2,
    "Player": "Player2",
    "Deck": "Burn",
    "Wins": 8,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 3,
    "Player": "Player3",
    "Deck": "Dimir Fae",
    "Wins": 7,
    "Losses": 1,
    "Win Rate": 0.875
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 4,
    "Player": "Player4",
    "Deck": "Izzet Fae",
    "Wins": 7,
    "Losses": 1,
    "Win Rate": 0.875
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 5,
    "Player": "Player5",
    "Deck": "Fog Tron",
    "Wins": 6,
    "Losses": 2,
    "Win Rate": 0.75
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 6,
    "Player": "Player6",
    "Deck": "Hexproof",
    "Wins": 6,
    "Losses": 2,
    "Win Rate": 0.75
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 7,
    "Player": "Player7",
    "Deck": "Boros Bully",
    "Wins": 5,
    "Losses": 3,
    "Win Rate": 0.625
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 8,
    "Player": "Player8",
    "Deck": "Mono Blue Delver",
    "Wins": 5,
    "Losses": 3,
    "Win Rate": 0.625
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 9,
    "Player": "Player9",
    "Deck": "Dimir Terror",
    "Wins": 4,
    "Losses": 4,
    "Win Rate": 0.5
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 10,
    "Player": "Player10",
    "Deck": "Gruul Land Destruction",
    "Wins": 4,
    "Losses": 4,
    "Win Rate": 0.5
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 11,
    "Player": "Player11",
    "Deck": "Boros Synth",
    "Wins": 3,
    "Losses": 5,
    "Win Rate": 0.375
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 12,
    "Player": "Player12",
    "Deck": "Stompy",
    "Wins": 3,
    "Losses": 5,
    "Win Rate": 0.375
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 13,
    "Player": "Player13",
    "Deck": "Defender Stampede",
    "Wins": 2,
    "Losses": 6,
    "Win Rate": 0.25
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 14,
    "Player": "Player14",
    "Deck": "Azorius Familiars",
    "Wins": 2,
    "Losses": 6,
    "Win Rate": 0.25
  },
  {
    "Date": "2025-01-10",
    "EventType": "offline",
    "Event": "Brazilian Nationals",
    "Rank": 15,
    "Player": "Player15",
    "Deck": "No Show",
    "Wins": 0,
    "Losses": 0,
    "Win Rate": 0
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 1,
    "Player": "Player1",
    "Deck": "Azorius Gates",
    "Wins": 10,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 2,
    "Player": "Player2",
    "Deck": "Orzhov Pestilence",
    "Wins": 10,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 3,
    "Player": "Player3",
    "Deck": "Jeskai Ephemerate",
    "Wins": 10,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 4,
    "Player": "Player4",
    "Deck": "Rakdos Storm",
    "Wins": 9,
    "Losses": 1,
    "Win Rate": 0.9
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 5,
    "Player": "Player5",
    "Deck": "Rakdos Madness",
    "Wins": 9,
    "Losses": 1,
    "Win Rate": 0.9
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 6,
    "Player": "Player6",
    "Deck": "Dimir Delver",
    "Wins": 9,
    "Losses": 1,
    "Win Rate": 0.9
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 7,
    "Player": "Player7",
    "Deck": "Mono Black Control",
    "Wins": 8,
    "Losses": 2,
    "Win Rate": 0.8
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 8,
    "Player": "Player8",
    "Deck": "Boros Monarch",
    "Wins": 8,
    "Losses": 2,
    "Win Rate": 0.8
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 9,
    "Player": "Player9",
    "Deck": "Jund",
    "Wins": 8,
    "Losses": 2,
    "Win Rate": 0.8
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 10,
    "Player": "Player10",
    "Deck": "Mono Red Blitz",
    "Wins": 7,
    "Losses": 3,
    "Win Rate": 0.7
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 11,
    "Player": "Player11",
    "Deck": "Cycle Storm",
    "Wins": 7,
    "Losses": 3,
    "Win Rate": 0.7
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 12,
    "Player": "Player12",
    "Deck": "Goblin Class Combo",
    "Wins": 7,
    "Losses": 3,
    "Win Rate": 0.7
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 13,
    "Player": "Player13",
    "Deck": "Orzhov Midrange",
    "Wins": 6,
    "Losses": 4,
    "Win Rate": 0.6
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 14,
    "Player": "Player14",
    "Deck": "Affinity",
    "Wins": 6,
    "Losses": 4,
    "Win Rate": 0.6
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 15,
    "Player": "Player15",
    "Deck": "Burn",
    "Wins": 6,
    "Losses": 4,
    "Win Rate": 0.6
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 16,
    "Player": "Player16",
    "Deck": "Dimir Fae",
    "Wins": 5,
    "Losses": 5,
    "Win Rate": 0.5
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 17,
    "Player": "Player17",
    "Deck": "Izzet Fae",
    "Wins": 5,
    "Losses": 5,
    "Win Rate": 0.5
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 18,
    "Player": "Player18",
    "Deck": "Fog Tron",
    "Wins": 5,
    "Losses": 5,
    "Win Rate": 0.5
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 19,
    "Player": "Player19",
    "Deck": "Hexproof",
    "Wins": 4,
    "Losses": 6,
    "Win Rate": 0.4
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 20,
    "Player": "Player20",
    "Deck": "Boros Bully",
    "Wins": 4,
    "Losses": 6,
    "Win Rate": 0.4
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 21,
    "Player": "Player21",
    "Deck": "Mono Blue Delver",
    "Wins": 4,
    "Losses": 6,
    "Win Rate": 0.4
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 22,
    "Player": "Player22",
    "Deck": "Dimir Terror",
    "Wins": 3,
    "Losses": 7,
    "Win Rate": 0.3
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 23,
    "Player": "Player23",
    "Deck": "Gruul Land Destruction",
    "Wins": 3,
    "Losses": 7,
    "Win Rate": 0.3
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 24,
    "Player": "Player24",
    "Deck": "Boros Synth",
    "Wins": 3,
    "Losses": 7,
    "Win Rate": 0.3
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 25,
    "Player": "Player25",
    "Deck": "Stompy",
    "Wins": 2,
    "Losses": 8,
    "Win Rate": 0.2
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 26,
    "Player": "Player26",
    "Deck": "Defender Stampede",
    "Wins": 2,
    "Losses": 8,
    "Win Rate": 0.2
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 27,
    "Player": "Player27",
    "Deck": "Azorius Familiars",
    "Wins": 2,
    "Losses": 8,
    "Win Rate": 0.2
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 28,
    "Player": "Player28",
    "Deck": "Elves",
    "Wins": 1,
    "Losses": 9,
    "Win Rate": 0.1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 29,
    "Player": "Player29",
    "Deck": "Azorius Gates",
    "Wins": 1,
    "Losses": 9,
    "Win Rate": 0.1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 30,
    "Player": "Player30",
    "Deck": "Orzhov Pestilence",
    "Wins": 1,
    "Losses": 9,
    "Win Rate": 0.1
  },
  {
    "Date": "2025-02-15",
    "EventType": "offline",
    "Event": "Paupergeddon",
    "Rank": 31,
    "Player": "Player31",
    "Deck": "Jeskai Ephemerate",
    "Wins": 0,
    "Losses": 10,
    "Win Rate": 0
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 1,
    "Player": "Player1",
    "Deck": "Affinity",
    "Wins": 9,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 2,
    "Player": "Player2",
    "Deck": "Burn",
    "Wins": 9,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 3,
    "Player": "Player3",
    "Deck": "Dimir Fae",
    "Wins": 9,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 4,
    "Player": "Player4",
    "Deck": "Izzet Fae",
    "Wins": 9,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 5,
    "Player": "Player5",
    "Deck": "Fog Tron",
    "Wins": 8,
    "Losses": 1,
    "Win Rate": 0.8888888888888888
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 6,
    "Player": "Player6",
    "Deck": "Hexproof",
    "Wins": 8,
    "Losses": 1,
    "Win Rate": 0.8888888888888888
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 7,
    "Player": "Player7",
    "Deck": "Boros Bully",
    "Wins": 8,
    "Losses": 1,
    "Win Rate": 0.8888888888888888
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 8,
    "Player": "Player8",
    "Deck": "Mono Blue Delver",
    "Wins": 8,
    "Losses": 1,
    "Win Rate": 0.8888888888888888
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 9,
    "Player": "Player9",
    "Deck": "Dimir Terror",
    "Wins": 7,
    "Losses": 2,
    "Win Rate": 0.7777777777777778
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 10,
    "Player": "Player10",
    "Deck": "Gruul Land Destruction",
    "Wins": 7,
    "Losses": 2,
    "Win Rate": 0.7777777777777778
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 11,
    "Player": "Player11",
    "Deck": "Boros Synth",
    "Wins": 7,
    "Losses": 2,
    "Win Rate": 0.7777777777777778
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 12,
    "Player": "Player12",
    "Deck": "Stompy",
    "Wins": 7,
    "Losses": 2,
    "Win Rate": 0.7777777777777778
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 13,
    "Player": "Player13",
    "Deck": "Defender Stampede",
    "Wins": 6,
    "Losses": 3,
    "Win Rate": 0.6666666666666666
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 14,
    "Player": "Player14",
    "Deck": "Azorius Familiars",
    "Wins": 6,
    "Losses": 3,
    "Win Rate": 0.6666666666666666
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 15,
    "Player": "Player15",
    "Deck": "Elves",
    "Wins": 6,
    "Losses": 3,
    "Win Rate": 0.6666666666666666
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 16,
    "Player": "Player16",
    "Deck": "Azorius Gates",
    "Wins": 6,
    "Losses": 3,
    "Win Rate": 0.6666666666666666
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 17,
    "Player": "Player17",
    "Deck": "Orzhov Pestilence",
    "Wins": 5,
    "Losses": 4,
    "Win Rate": 0.5555555555555556
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 18,
    "Player": "Player18",
    "Deck": "Jeskai Ephemerate",
    "Wins": 5,
    "Losses": 4,
    "Win Rate": 0.5555555555555556
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 19,
    "Player": "Player19",
    "Deck": "Rakdos Storm",
    "Wins": 5,
    "Losses": 4,
    "Win Rate": 0.5555555555555556
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 20,
    "Player": "Player20",
    "Deck": "Rakdos Madness",
    "Wins": 5,
    "Losses": 4,
    "Win Rate": 0.5555555555555556
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 21,
    "Player": "Player21",
    "Deck": "Dimir Delver",
    "Wins": 4,
    "Losses": 5,
    "Win Rate": 0.4444444444444444
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 22,
    "Player": "Player22",
    "Deck": "Mono Black Control",
    "Wins": 4,
    "Losses": 5,
    "Win Rate": 0.4444444444444444
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 23,
    "Player": "Player23",
    "Deck": "Boros Monarch",
    "Wins": 4,
    "Losses": 5,
    "Win Rate": 0.4444444444444444
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 24,
    "Player": "Player24",
    "Deck": "Jund",
    "Wins": 4,
    "Losses": 5,
    "Win Rate": 0.4444444444444444
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 25,
    "Player": "Player25",
    "Deck": "Mono Red Blitz",
    "Wins": 3,
    "Losses": 6,
    "Win Rate": 0.3333333333333333
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 26,
    "Player": "Player26",
    "Deck": "Cycle Storm",
    "Wins": 3,
    "Losses": 6,
    "Win Rate": 0.3333333333333333
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 27,
    "Player": "Player27",
    "Deck": "Goblin Class Combo",
    "Wins": 3,
    "Losses": 6,
    "Win Rate": 0.3333333333333333
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 28,
    "Player": "Player28",
    "Deck": "Affinity",
    "Wins": 3,
    "Losses": 6,
    "Win Rate": 0.3333333333333333
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 29,
    "Player": "Player29",
    "Deck": "Burn",
    "Wins": 2,
    "Losses": 7,
    "Win Rate": 0.2222222222222222
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 30,
    "Player": "Player30",
    "Deck": "Dimir Fae",
    "Wins": 2,
    "Losses": 7,
    "Win Rate": 0.2222222222222222
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 31,
    "Player": "Player31",
    "Deck": "Izzet Fae",
    "Wins": 2,
    "Losses": 7,
    "Win Rate": 0.2222222222222222
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 32,
    "Player": "Player32",
    "Deck": "Fog Tron",
    "Wins": 2,
    "Losses": 7,
    "Win Rate": 0.2222222222222222
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 33,
    "Player": "Player33",
    "Deck": "Hexproof",
    "Wins": 1,
    "Losses": 8,
    "Win Rate": 0.1111111111111111
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 34,
    "Player": "Player34",
    "Deck": "Boros Bully",
    "Wins": 1,
    "Losses": 8,
    "Win Rate": 0.1111111111111111
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 35,
    "Player": "Player35",
    "Deck": "Mono Blue Delver",
    "Wins": 1,
    "Losses": 8,
    "Win Rate": 0.1111111111111111
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 36,
    "Player": "Player36",
    "Deck": "Dimir Terror",
    "Wins": 1,
    "Losses": 8,
    "Win Rate": 0.1111111111111111
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 37,
    "Player": "Player37",
    "Deck": "Gruul Land Destruction",
    "Wins": 0,
    "Losses": 9,
    "Win Rate": 0
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 38,
    "Player": "Player38",
    "Deck": "Boros Synth",
    "Wins": 0,
    "Losses": 9,
    "Win Rate": 0
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 39,
    "Player": "Player39",
    "Deck": "Stompy",
    "Wins": 0,
    "Losses": 9,
    "Win Rate": 0
  },
  {
    "Date": "2025-03-01",
    "EventType": "online",
    "Event": "MTG Arena Open",
    "Rank": 40,
    "Player": "Player40",
    "Deck": "Defender Stampede",
    "Wins": 0,
    "Losses": 9,
    "Win Rate": 0
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 1,
    "Player": "Player1",
    "Deck": "Affinity",
    "Wins": 7,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 2,
    "Player": "Player2",
    "Deck": "Burn",
    "Wins": 7,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 3,
    "Player": "Player3",
    "Deck": "Dimir Fae",
    "Wins": 7,
    "Losses": 0,
    "Win Rate": 1
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 4,
    "Player": "Player4",
    "Deck": "Izzet Fae",
    "Wins": 6,
    "Losses": 1,
    "Win Rate": 0.8571428571428571
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 5,
    "Player": "Player5",
    "Deck": "Fog Tron",
    "Wins": 6,
    "Losses": 1,
    "Win Rate": 0.8571428571428571
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 6,
    "Player": "Player6",
    "Deck": "Hexproof",
    "Wins": 6,
    "Losses": 1,
    "Win Rate": 0.8571428571428571
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 7,
    "Player": "Player7",
    "Deck": "Boros Bully",
    "Wins": 5,
    "Losses": 2,
    "Win Rate": 0.7142857142857143
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 8,
    "Player": "Player8",
    "Deck": "Mono Blue Delver",
    "Wins": 5,
    "Losses": 2,
    "Win Rate": 0.7142857142857143
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 9,
    "Player": "Player9",
    "Deck": "Dimir Terror",
    "Wins": 5,
    "Losses": 2,
    "Win Rate": 0.7142857142857143
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 10,
    "Player": "Player10",
    "Deck": "Gruul Land Destruction",
    "Wins": 4,
    "Losses": 3,
    "Win Rate": 0.5714285714285714
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 11,
    "Player": "Player11",
    "Deck": "Boros Synth",
    "Wins": 4,
    "Losses": 3,
    "Win Rate": 0.5714285714285714
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 12,
    "Player": "Player12",
    "Deck": "Stompy",
    "Wins": 4,
    "Losses": 3,
    "Win Rate": 0.5714285714285714
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 13,
    "Player": "Player13",
    "Deck": "Defender Stampede",
    "Wins": 3,
    "Losses": 4,
    "Win Rate": 0.42857142857142855
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 14,
    "Player": "Player14",
    "Deck": "Azorius Familiars",
    "Wins": 3,
    "Losses": 4,
    "Win Rate": 0.42857142857142855
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 15,
    "Player": "Player15",
    "Deck": "Elves",
    "Wins": 3,
    "Losses": 4,
    "Win Rate": 0.42857142857142855
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 16,
    "Player": "Player16",
    "Deck": "Azorius Gates",
    "Wins": 2,
    "Losses": 5,
    "Win Rate": 0.2857142857142857
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 17,
    "Player": "Player17",
    "Deck": "Orzhov Pestilence",
    "Wins": 2,
    "Losses": 5,
    "Win Rate": 0.2857142857142857
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 18,
    "Player": "Player18",
    "Deck": "Jeskai Ephemerate",
    "Wins": 2,
    "Losses": 5,
    "Win Rate": 0.2857142857142857
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 19,
    "Player": "Player19",
    "Deck": "Rakdos Storm",
    "Wins": 1,
    "Losses": 6,
    "Win Rate": 0.14285714285714285
  },
  {
    "Date": "2025-03-04",
    "EventType": "online",
    "Event": "MTGO Open",
    "Rank": 20,
    "Player": "Player20",
    "Deck": "Rakdos Madness",
    "Wins": 1,
    "Losses": 6,
    "Win Rate": 0.14285714285714285
  }
];